name: âš™ï¸ CI
on:
  pull_request: 
    branches:
      - main

jobs:
  # validate-commits:
  #   name: test cangulo-actions/conventional-commits-validator
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v4

  #     - name: Validate Conventional Commits
  #       # this must target main or a valid branch in the cangulo-actions/conventional-commits-validator repo
  #       uses: cangulo-actions/conventional-commits-validator@main
  #       id: validate-commits
  #       with:
  #         configuration: semver-commits.yml
  #         add-next-release-type-as-label-to-pr: true
  #         add-commit-types-as-labels-to-pr: true
  #         add-commit-scopes-as-labels-to-pr: true

  create-check-run:
    name: ğŸ‘®â€â™‚ï¸ create output
    runs-on: ubuntu-latest
    # outputs:
    #   commit-valid: ${{ steps.create-output.outputs.commit-valid }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      # - name: Create output
      #   uses: actions/github-script@v7.0.1
      #   id: create-output
      #   with:
      #     script: |
      #       github.rest.issues.get({
      #         issue_number: context.issue.number,
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #       })

      #       core.setOutput('commit-valid', 'true')  

# refresh 2023-11-27